name: stroll_app
description: "A modern dating app connecting you with meaningful matches, one step at a time."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/background_image.jpg
    - assets/images/user_photo.jpg
    - assets/icons/

fonts:
  - family: ProximaNova
    fonts:
      - asset: assets/fonts/Proxima_Nova_Regular.ttf
      - asset: assets/fonts/Proxima_Nova-Bold.ttf
        weight: 700
      - asset: assets/fonts/Proxima_Nova-Italic.ttf
        style: italic
